### ISSUE TITLE
Exit Code 1 when adding the Package

### ISSUE THREAD

**Issue by ben55j** [augustkimo/instagram_media#1]
Hello, 
I am running this error on when running get packages

Because every version of instagram_media depends on http ^0.12.0 and insta_public_api 0.1.2 depends on http ^0.13.3, instagram_media is incompatible with insta_public_api 0.1.2.
And because no versions of insta_public_api match >0.1.2 <0.2.0, instagram_media is incompatible with insta_public_api ^0.1.2.
So, because services_adom_pro depends on both insta_public_api ^0.1.2 and instagram_media ^0.0.11, version solving failed.
pub get failed (1; So, because services_adom_pro depends on both insta_public_api ^0.1.2 and instagram_media ^0.0.11, version solving failed.)
exit code 1

Here my .yaml file

```

name: services_adom_pro
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.

version: 1.0.0+17

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  google_fonts: ^2.1.0
  animated_text_kit: ^4.2.1
  mailto: ^2.0.0
  url_launcher: ^6.0.9
  adaptive_dialog: ^1.1.0
  share: ^2.0.4
  flutter_rating_bar: ^4.0.0
  sliver_fab: ^1.0.0
  easy_dialog: ^1.1.0
  animated_splash_screen: ^1.1.0
  page_transition: ^2.0.1-nullsafety.0
  cached_network_image: ^3.1.0
  time: ^2.0.0
  timezone: ^0.7.0
  intl: ^0.17.0
  awesome_dialog: ^2.1.0
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  firebase_messaging: ^10.0.4
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  string_validator: ^0.3.0
  modal_progress_hud: ^0.1.3
  image_picker: ^0.8.2
  shared_preferences: ^2.0.6
  get: ^4.3.0
  modal_bottom_sheet: ^2.0.0
  carousel_slider: ^4.0.0
  maps_launcher: ^2.0.0
  connectivity: ^3.0.6
  webview_flutter_plus: ^0.2.2
  paginate_firestore: ^1.0.2
  firebase_dynamic_links: ^2.0.9
  permission_handler: ^8.1.4+1

  #to Update the Icon run:flutter pub run flutter_launcher_icons:main

  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  readmore: ^2.1.0
  rate_my_app: ^1.1.1
  firebase_analytics: ^8.3.3
  facebook_app_events: ^0.14.7
  insta_public_api: ^0.1.2
  instagram_media: ^0.0.11
  http: ^0.13.4


  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.jpg"
  adaptive_icon_background: "assets/icons/Android_adaptive_icon_background.png"
  adaptive_icon_foreground: "assets/icons/Android_adaptive_icon_foreground.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/services/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```
